# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: passwd_goes_here
  CLOUD_SQL_DATABASE_NAME: postgres
  CLOUD_SQL_CONNECTION_NAME: connection_name

# [END gae_python37_cloudsql_config]
